### ISSUE TITLE
Release builds issue

### ISSUE THREAD

**Issue by CaitSith2** [Berserker66/MultiWorld-Utilities#47]
The BerserkerMultiClient.exe within the python 3.7 and python 3.8 releases do not work correctly, 

https://i.imgur.com/bXbGy1A.png - Python 3.7
https://i.imgur.com/2C1x1Hx.png - Python 3.8

However, the one that does work correctly, and the only one that is working correctly, is the one in the All in One release. https://i.imgur.com/OEwitTg.png

**Comment by CaitSith2** [comment]
In both cases of the not working correctly versions,  ```Traceback (most recent call last):
  File "__startup__.py", line 40, in run
  File "Console.py", line 37, in run
  File "MultiClient.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "aioconsole\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "aioconsole\code.py", line 36, in <module>
  File "aioconsole\code.py", line 67, in AsynchronousConsole
NameError: name 'help' is not defined
Press enter to close.```

**Comment by Berserker66** [comment]
Oh, yeah. I had to to some manual hacking of aioconsole to get it to work in compilation. 
https://github.com/anthony-tuininga/cx_Freeze/issues/578

Might just remove the appveyor builds till that's fixed by someone.
